name: Notion Sync

on:
  workflow_dispatch:   # 수동 실행 버튼 생성

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install notion-to-md
        run: npm install notion-to-md

      - name: Fetch Notion posts
        run: npx notion-to-md -k ${{ secrets.NOTION_API_KEY }} -i 2780d24dfb748022b0f9ca774059605c -o ./_posts

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync from Notion"
          git push
